### ISSUE TITLE
Misspelled word "mordium"

### ISSUE THREAD

**Issue by christinaspy** [pretix/pretix-modirum#1]
Hello @pc-coholic 

I'm trying to install Pretix-Modirum with Docker and I'm getting this error:

![error](https://user-images.githubusercontent.com/20626803/68295944-255d6f80-009c-11ea-9a08-b3b1beebb01f.PNG)

I noticed that on this file: 
pretix_modirum/templates/pretix_modirum/redirecting.html

You misspell the word "mordium".

Can you please fix this?

Thank you

CC @raphaelm

**Comment by raphaelm** [comment]
@christinaspy I'm so sorry! We fixed this immediately in b86f314
